module.exports = {
    tutorialSidebar: [
        {
            type: 'category',
            label: 'Basics',
            items: [
                'CSS/Basics/variables',
                'CSS/Basics/typographie',
                'CSS/Basics/couleurs-et-degrades',
            ],
        },
        {
            type: 'category',
            label: 'Helpers',
            items: [
                'CSS/Helpers/spacing',
                'CSS/Helpers/flex-et-inline-flex',
                'CSS/Helpers/text',
                'CSS/Helpers/colors',
                'CSS/Helpers/links-ajouter-icon-link',
                'CSS/Helpers/stretched-links',
                'CSS/Helpers/responsive',
                'CSS/Helpers/ratio',
                'CSS/Helpers/truncate',
                'CSS/Helpers/centered',
                'CSS/Helpers/object-fit',
                'CSS/Helpers/position-overflow',
                'CSS/Helpers/shadow',
                'CSS/Helpers/clearfix',
            ],
        },
        {
            type: 'category',
            label: 'Layout',
            items: [
                'CSS/Layout/sections',
                'CSS/Layout/max-widths',
                'CSS/Layout/topbar',
                'CSS/Layout/menu-submenu',
                'CSS/Layout/mobile-menu',
                'CSS/Layout/footer-light-dark-versions',
            ],
        },
        {
            type: 'category',
            label: 'Forms',
            items: [
                'CSS/Forms/markup',
                'CSS/Forms/simple-input',
                'CSS/Forms/select',
                'CSS/Forms/checks-radios',
                'CSS/Forms/input-group',
                'CSS/Forms/validation',
                'CSS/Forms/dropzone',
            ],
        },
        {
            type: 'category',
            label: 'Components',
            items: [
                'CSS/Components/flash-messages',
                'CSS/Components/boutons',
                'CSS/Components/icones',
                'CSS/Components/badge',
                'CSS/Components/card',
                'CSS/Components/dropdowns-selectize',
                'CSS/Components/pagination',
                'CSS/Components/spinners',
                'CSS/Components/separator-avec-et-ou-au-milieu-du-trait',
            ],
        },
        {
            type: 'category',
            label: 'Plugins',
            items: [
                'CSS/Plugins/fancybox',
                'CSS/Plugins/slick-slider',
                'CSS/Plugins/selectize',
                'CSS/Plugins/sweetalert',
                'CSS/Plugins/sortable',
            ],
        },
    ],
    laravelSidebar: [
        {
            type: 'category',
            label: 'Installation Step by Step',
            items: [
                'laravel/Installation/StepByStep/laravel',
                'laravel/Installation/StepByStep/packages-composer',
                'laravel/Installation/StepByStep/vite-app',
                'laravel/Installation/StepByStep/layout-principal',
                'laravel/Installation/StepByStep/routes-controllers',
                'laravel/Installation/StepByStep/jquery-plugins',
            ],
        },
        {
            type: 'doc',
            id: 'laravel/Installation/package-laravel',
        },
        {
            type: 'category',
            label: 'Configuration détaillée',
            items: [
                'laravel/Features/web-php',
                'laravel/Features/jquery',
                'laravel/Features/jm-menu',
                'laravel/Features/jm-sections',
                'laravel/Features/jm-flash',
                'laravel/Features/jm-metas',
                'laravel/Features/notiflix',
                'laravel/Features/fancybox',
                'laravel/Features/blade-icons',
                'laravel/Features/laravel-form-components',
                'laravel/Features/dropzone',
                'laravel/Features/create-form',
                'laravel/Features/pagination',
                'laravel/Features/install-from-repo',
            ],
        },
        {
            type: 'category',
            label: 'Guides',
            items: [
                'laravel/Guides/troubleshooting',
            ],
        },
        {
            type: 'category',
            label: 'Deprecated',
            collapsed: true,
            items: [
                'laravel/Archived/nova',
                'laravel/Archived/laravel-nova',
                'laravel/Archived/nova-video-field',
                'laravel/Archived/nova-belongsToMany',
                'laravel/Archived/add-ckeditor',
            ],
        }
    ],
    forgeSidebar: [
        {
            type: 'doc',
            id: 'Deployment/intro',
        },
    ],
};
